refactor: 예외, VO 관련 컨벤션 적용
Songusika/woowa-announcement-attendance pull request #11
Opened 2023-11-04 05:41 UTC by yujamint

## 👨🏻‍💻 작업 사항
- VO에 data class를 적용했습니다.
- 기존에 if 문으로 처리하고 있던 예외 검증을 `require()`를 사용하도록 수정했습니다.
- 커스텀 예외를 대부분 삭제했습니다. (관련 내용 기타 사항에서 더 자세하게 다루겠습니다.)

## 💬 기타 사항
### 인증/인가 관련 Exception 유지
코드 컨벤션을 정할 때, `require()`, `check()`를 적극 활용 및 커스텀 예외는 사용하지 않는 것으로 결정했습니다.
하지만 인증/인가와 관련된 커스텀 예외는 필요하다고 생각했습니다.

먼저, `IllegalArgumentException`의 핸들러는 BadRequest(400) 상태 코드를 반환한다는 것을 전제로 하겠습니다.

[인수 조건](https://mrjun.notion.site/fc4fb053bc8b4e468f5e4a05c2b08c09?v=8bf831d49c934347accd193734c6a9f2&p=ff9be1634f474eff99b94e3b334577eb&pm=s)을 보면 인증/인가가 실패한 API의 응답으로 401 상태 코드를 반환하고 있습니다.
이때 인증/인가 관련 예외도 IAE를 발생시킨다면 IAE의 핸들러는 400 상태 코드를 반환하기 때문에, 인증/인가 관련 예외도 IAE로는 처리하는 것은 적합하지 않다는 생각입니다.
인수 조건과 같이 401을 반환하는 커스텀 예외가 필요하다고 생각하였습니다.

위와 같은 이유로 `AuthorizationException`이라는 커스텀 예외와, 401 상태 코드를 반환하는 핸들러는 유지하는 것으로 코드 작업을 진행했습니다.
의견 남겨주시기 바랍니다!

2023-11-04 05:43 UTC, yujamint commented on backend/src/main/kotlin/com/woowahan/campus/announcement/exception/AnnouncementExceptionHandler.kt
> +    @ExceptionHandler(IllegalArgumentException::class, IllegalStateException::class)
여러 Exception 클래스를 한 번에 선언할 수 있다는 점에서 `@ExceptionHandler`에 예외를 정의하는 방식으로 코드를 수정했습니다.

이전처럼 파라미터로만 정의하는 방식과 현재 방식 중 어떤 것이 더 나은가요??

2023-11-04 05:48 UTC, drunkenhw reviewed
수고하셨습니다

2023-11-04 05:48 UTC, drunkenhw commented on backend/src/main/kotlin/com/woowahan/campus/announcement/domain/Announcement.kt
> +        }
해당 검증을 vo에서 하지 않는 이유가 있나요?

2023-11-04 05:48 UTC, drunkenhw commented on backend/src/main/kotlin/com/woowahan/campus/announcement/domain/Author.kt
> +            "공지의 작성자는 1자 이상, 20자 이하로 작성 가능합니다."
trim을 하는 이유가 무엇인가요?

2023-11-04 05:48 UTC, drunkenhw commented on backend/src/main/kotlin/com/woowahan/campus/announcement/domain/Content.kt
> +            "공지의 내용은 1자 이상, 65,535자 이하로 작성 가능합니다."
trim을 하는 이유가 무엇인가요

2023-11-04 05:48 UTC, drunkenhw commented on backend/src/main/kotlin/com/woowahan/campus/announcement/exception/AnnouncementExceptionHandler.kt
> +    @ExceptionHandler(IllegalArgumentException::class, IllegalStateException::class)
저는 파라미터가 좋아요

2023-11-04 05:48 UTC, drunkenhw commented on backend/src/main/kotlin/com/woowahan/campus/announcement/exception/AuthorizationException.kt
> +class AuthorizationException(message: String) : RuntimeException(message)
이 커스텀 예외는 살아있는 이유가 뭔가요

2023-11-04 05:48 UTC, drunkenhw commented on backend/src/main/kotlin/com/woowahan/campus/announcement/feature/CreateAnnouncement.kt
> +            Announcement(
create로 생성하지 않는 이유가 뭔가요

2023-11-04 06:18 UTC, yujamint commented on backend/src/main/kotlin/com/woowahan/campus/announcement/domain/Announcement.kt
> +        }
VO에서 하는 게 좋아보이네요. 반영했습니다👍

2023-11-04 06:23 UTC, yujamint commented on backend/src/main/kotlin/com/woowahan/campus/announcement/domain/Author.kt
> +            "공지의 작성자는 1자 이상, 20자 이하로 작성 가능합니다."
Author의 앞,뒤로 공백이 들어가는 게 필요하지 않고, 적절하지도 않다고 생각했습니다. ` 박스터` == `박스터 `

2023-11-04 06:25 UTC, drunkenhw commented on backend/src/main/kotlin/com/woowahan/campus/announcement/domain/Author.kt
> +            "공지의 작성자는 1자 이상, 20자 이하로 작성 가능합니다."
그 부분에 대한 규칙을 정했나요? 그리고 멋대로 잘라도 될까요? 이름이 공백으로 시작하고 싶을 수도 있지 않을까요?

2023-11-04 06:27 UTC, yujamint commented on backend/src/main/kotlin/com/woowahan/campus/announcement/domain/Author.kt
> +            "공지의 작성자는 1자 이상, 20자 이하로 작성 가능합니다."
지금 보니까 trim을 한 값을 할당해주고 있지도 않군요.. ㅋㅋㅋ
일단 정해지지 않은 규칙이니 없애도록 하겠습니다~

2023-11-04 06:28 UTC, yujamint commented on backend/src/main/kotlin/com/woowahan/campus/announcement/domain/Author.kt
> +            "공지의 작성자는 1자 이상, 20자 이하로 작성 가능합니다."
Author에는 닉네임이 들어갈텐데 공백을 허용하는 게 적절한지에는 의문이 들긴 합니다!

2023-11-04 06:28 UTC, yujamint commented on backend/src/main/kotlin/com/woowahan/campus/announcement/exception/AuthorizationException.kt
> +class AuthorizationException(message: String) : RuntimeException(message)
PR 메세지의 기타 사항 참고해 주세요!

2023-11-04 06:29 UTC, yujamint commented on backend/src/main/kotlin/com/woowahan/campus/announcement/feature/CreateAnnouncement.kt
> +            Announcement(
어차피 VO로 받기로 결정했으니, Announcement의 주 생성자를 쓰는 것이 적절하다고 생각했습니다.
원래는 String을 받아서 VO로 만들어 준다는 점에서 주 생성자와 차이가 있다고 생각했으나, 이제는 차이가 없는 것 같아서요.

2023-11-04 06:29 UTC, drunkenhw commented on backend/src/main/kotlin/com/woowahan/campus/announcement/feature/CreateAnnouncement.kt
> +            Announcement(
제가 작성한 로직 좀 읽어주세요

2023-11-04 06:31 UTC, drunkenhw commented on backend/src/main/kotlin/com/woowahan/campus/announcement/feature/CreateAnnouncement.kt
> +            Announcement(
아 블랙캣이 푸시안했군요 어제 그럼 다시 제가 추가할게오ㅛ

2023-11-04 06:32 UTC, yujamint commented on backend/src/main/kotlin/com/woowahan/campus/announcement/feature/CreateAnnouncement.kt
> +            Announcement(
넵~~

2023-11-04 06:33 UTC, yujamint commented on backend/src/main/kotlin/com/woowahan/campus/announcement/exception/AnnouncementExceptionHandler.kt
> +    @ExceptionHandler(IllegalArgumentException::class, IllegalStateException::class)
같은 처리를 해줄 것이라면, 2개의 ExceptionHandler를 만드는 것보다 여러 개의 Exception을 처리하는 한 Handler에서 처리하는 것이 좋다고 생각했습니다.
이 부분은 팀원들 의견에 따라 결정하겠습니다~

2023-11-06 05:57 UTC, Songusika requested changes
고생하셨습니다 민트!

참고로 아직 후행쉼표가 없는 부분이 있는데 해당 부분은 수정해주세요!!

2023-11-06 05:57 UTC, Songusika commented on backend/src/main/kotlin/com/woowahan/campus/announcement/domain/AnnouncementValidator.kt
> +            "존재하지 않는 슬랙 채널입니다."
`toLong()` 부분은 yml 명세 때문인 것 같아요!
yml 명세에서 `format`을 `int64` 로 변경하면 Long 타입으로 받을 수 있어요!

2023-11-06 05:57 UTC, Songusika commented on backend/src/main/kotlin/com/woowahan/campus/announcement/domain/Author.kt
> +            "공지의 작성자는 1자 이상, 20자 이하로 작성 가능합니다."
```suggestion
            "공지의 작성자는 1자 이상, ${MAX_LENGTH}자 이하로 작성 가능합니다." 
```
문자열 템플릿을 활용해보는건 어떨까요? 😊

2023-11-06 05:57 UTC, Songusika commented on backend/src/main/kotlin/com/woowahan/campus/announcement/feature/UpdateAnnouncement.kt
>          )
저희 저번 회의에 따르면 엔티티 상태 업데이트 이후에 `dirty checking`에 의존하지 않고
도메인 이벤트 사용 등의 이유로 레포지터리의 `save()` 호출하기로 했습니다!

2023-11-07 05:43 UTC, thdwoqor approved these changes
고생하셨습니다.

2023-11-07 05:43 UTC, thdwoqor commented on backend/src/main/kotlin/com/woowahan/campus/announcement/exception/AnnouncementExceptionHandler.kt
> +    @ExceptionHandler(IllegalArgumentException::class, IllegalStateException::class)
저는 지금방식이 좋습니다

2023-11-07 08:14 UTC, yujamint commented on backend/src/main/kotlin/com/woowahan/campus/announcement/domain/AnnouncementValidator.kt
> +            "존재하지 않는 슬랙 채널입니다."
해당 부분 수정했습니다~

2023-11-07 08:15 UTC, yujamint commented on backend/src/main/kotlin/com/woowahan/campus/announcement/feature/UpdateAnnouncement.kt
>          )
`Announcement.update()`에서 도메인 이벤트를 추가하고, `UpdateAnnouncement`에서는 save를 함으로써 이벤트 발행 및 처리하도록 수정했습니다~

2023-11-07 12:16 UTC, Songusika requested changes
고생했습니다 민트!
공지 생성과 관련되어서 반영해야할 부분이 있어서 RC 남겼습니다!
추후에 모든 공지를 조회하는 부분에서 int64 만 반영안되게 주의하면 되겠네요!!

2023-11-07 12:16 UTC, Songusika commented on backend/src/main/kotlin/com/woowahan/campus/announcement/domain/Announcement.kt
>      }
정적 팩터리 메서드가 아닌, 일반 주생성자로 생성한 공지는 슬랙 알림이 발송이 안되겠네요!
이를 위해서 `init` 블럭에서 이벤트를 발송하거나, 주 생성자에 `private constructor` 키워드를 붙여서 정적팩터리 메서드만 사용하게 하는건 어떨까요?

2023-11-07 12:16 UTC, Songusika commented on backend/src/main/kotlin/com/woowahan/campus/announcement/domain/AnnouncementRepository.kt
> +    fun findById(id: Long): Announcement?
확장 함수를 이용해 레포지터리 파일에 공지 조회와 존재하지 않는 공지에 대한 예외를 책임을 위임하면 좋을 거 같습니다.

2023-11-07 12:16 UTC, Songusika commented on backend/build.gradle.kts
> +    testImplementation("com.ninja-squad:springmockk:3.0.1")
혹시 mockk 만 명시적으로 주석과 공백을 추가한 이유가 있을까요?
다른 의존성 처럼 붙이면 더 보기 좋을 거 같아요!

2023-11-07 23:47 UTC, yujamint commented on backend/src/main/kotlin/com/woowahan/campus/announcement/domain/Announcement.kt
>      }
오우 맞네요~ 정적 팩토리 메서드만을 호출할 수 있도록 private constructor로 수정했습니다!

2023-11-08 00:01 UTC, yujamint commented on backend/src/main/kotlin/com/woowahan/campus/announcement/domain/AnnouncementRepository.kt
> +    fun findById(id: Long): Announcement?
좋습니다!
문득 예외처리를 서비스에서 하는 게 좋을지, 인터페이스에서 하는 게 좋을지 궁금해져서 찾아봤습니다.
[인프런의 한 Q&A 글](https://www.inflearn.com/questions/891531/%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC-%EB%A6%AC%ED%8C%A9%ED%86%A0%EB%A7%81-%EC%A7%88%EB%AC%B8)의 답변에 상당히 공감이 돼서 공유합니다.

2023-11-08 00:02 UTC, yujamint commented on backend/build.gradle.kts
> +    testImplementation("com.ninja-squad:springmockk:3.0.1")
전 이렇게 관리하는 한 눈에 잘 들어오더라고요 ㅋㅋㅋ..
일단은 컨벤션을 정한 적이 없기 때문에 원래의 형태를 유지하겠습니다!

2023-11-08 01:31 UTC, Songusika commented on backend/build.gradle.kts
> +    testImplementation("com.ninja-squad:springmockk:3.0.1")
사실 저도 민트 방식이 보기 편하더라구요!

2023-11-08 01:34 UTC, Songusika commented on backend/src/main/kotlin/com/woowahan/campus/announcement/domain/AnnouncementRepository.kt
> +    fun findById(id: Long): Announcement?
좋은 글 공유 감사합니다~

2023-11-08 06:08 UTC, merged